# Generated by Django 3.0.7 on 2020-06-27 11:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, unique=True)),
                ('Description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Open', max_length=100)),
                ('Type', models.CharField(default='General', max_length=100, null=True)),
                ('scheduled', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('parentActivityId', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FavLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('link', models.CharField(default='no link', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Description', models.CharField(max_length=200, unique=True)),
                ('Task_Title', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default='A', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_cryptography.fields.encrypt(tinymce.models.HTMLField(null=True))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectTask')),
            ],
        ),
        migrations.CreateModel(
            name='ApplictaionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Value', models.CharField(max_length=200)),
                ('IsCategory', models.BooleanField(null=True)),
                ('Description', models.CharField(max_length=200)),
                ('Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ApplictaionData')),
            ],
        ),
    ]
