# Generated by Django 3.0.7 on 2020-06-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
