# Generated by Django 3.0.7 on 2020-06-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200627_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='Task_Title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
