# Generated by Django 3.0.7 on 2020-06-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200628_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='Task_Title',
            field=models.TextField(unique=True),
        ),
    ]
